# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Dirs
alias_dir="$HOME/.config/bash/aliases"
fn_dir="$HOME/.config/bash/functions"

# Set up exports
export EDITOR=helix
export VISUAL="$EDITOR"

# Auto-load all custom bash aliases
for file in "$alias_dir"/*; do
    [[ -f "$file" && -r "$file" ]] && . "$file"
done

# Auto-load all custom bash functions
for file in "$fn_dir"/*; do
    [[ -f "$file" && -r "$file" ]] && . "$file"
done

# Load GHCup, for some reason this overwrites the path
# Paths below won't exist if this happes after
if [[ -f "$HOME/.ghcup/env" ]]; then
    . "$HOME/.ghcup/env"
fi

# Set up paths, after loading functions
paths=(
    "$HOME/.npm/bin"
    "$HOME/.local/bin"
    "$HOME/bin"
    "$HOME/.cargo/bin"
)

# add_to_path defined in a function file
for path in "${paths[@]}"; do
    add_to_path "$path"
done

# Load starship
if command -v starship >/dev/null 2>&1; then
  eval "$(starship init bash)"
fi
